version: '3.7'

services:
  nginx:
    image: nginx:latest
    networks:
      - traefik-proxy-net
      - nginx-net
    labels:
      - traefik.frontend.rule=Host:domain.tld
      - traefik.docker.network:proxy-net
      - traefik.port=80
      - traefik.enable=true

networks:
  traefik-proxy-net:
    external: true
    name: proxy-net
  nginx-net:
    name: nginx-net
