version: '3.7'


services:
  traefik_reverse_proxy:
    image: traefik:v1.7.8
    networks:
      - proxy_frontend
    ports:
      - target: 80
        protocol: tcp
        published: 80
        mode: ingress
      - target: 443
        protocol: tcp
        published: 443
        mode: ingress
    labels:
      - traefik.frontend.rule=Host:traefik.familyfood.xyz
      - traefik.docker.network=${PROXY_DOCKER_NETWORK}
      - traefik.port=8080
      - traefik.enable=true
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

networks:
  proxy_frontend:
    name: ${PROXY_DOCKER_NETWORK}
